[package]
name = "katexit-example-nightly"
description = "Rendered example of katexit with nightly rustc"

version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies.katexit]
version = "0.1.5"
path = "../katexit"
